// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfoencnakiqopgdcnetc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmb2VuY25ha2lxb3BnZGNuZXRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2OTk2NTcsImV4cCI6MjA2MTI3NTY1N30.EixJrCSvNLdC4YxrUTwDTCA30xtLGVFVsHKeo2c4e4g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);